name: Regression Automation Test 03

on:
  push:
    branches: [master]
  pull_request:
    branches : [master]

jobs:
  run-automated-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
   
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
       
    - name: Install Chrome
      run: |
        sudo wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        sudo echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google.list
        sudo apt update
        sudo apt install -y google-chrome-stable
        google-chrome --version
         
       
    - name: local Maven repository
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven
        restore-keys: |
          ${{ runner.os }}-maven
         
    - name: Maven verify Test
      run: mvn -B clean verify
